spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:istar588/config-repo1.git
          ignore-local-ssh-settings: true
          host-key: "AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
          host-key-algorithm: ssh-rsa
          private-key: |
                    -----BEGIN RSA PRIVATE KEY-----
                    MIICXAIBAAKBgQDKYwyI5UIuxjZXvFFhbqB5FxIfD+MS9Ae5A94k7mCBwxNi9lb4
                    XcF5KLvM1hh8ebs4OfrfaNIHRsuPtlf3R57jxrU63avMuKPr/wUiWgV6i9ibsqD+
                    IwLXeC8EkeSkenMSwPoMlMvorcoQyLCZoHYsoiSieQdQpn8GY8xwslYK5wIDAQAB
                    AoGAbblzk0iQMCHAVqK/kE5U7DGI3pRTbPQmt7UUG/utEMz9Vrrtfev+t7xQzQYJ
                    8npg+WPd0n/W1qEYPcsDOAp5ZldqS+FNvllFnNjiDtA3pA7E5JWw/NV+f3fWPKzm
                    /rH5yLRrWzlRsiAQp1GaRrTaVty6XYhlKQHu7GjREJ0RXaECQQDqbGuHQTFDA//C
                    bkim/H81AX5wx9tEO9r4PPqG2poCNMOBgLXgbCh99x85Uhx5PRWKCMLW3A08K5mK
                    mWWdrEpRAkEA3QPFC2ajy6cC+q3HYAfOLsQ97XWaVvQypIyCng1LEdmboF21zi7N
                    2ztiWEo7xGKDf/AqkvutxG6K0NhsVvh7twJBAIhjwEQXSAQHpZyH8blGGvTKA7i2
                    bvpKIOJhCBnBwe0aqc0FB8yk4QI472+4OFzJj2iaJFJCAWlKrLCZAygzf6ECQEZS
                    7b678QBa6urCor7enO9qh93n3q0uVHLhNqp9xlYurIMxbijl4aCRW7CGJlBNnFP4
                    IkPUiy0Gk2rygj6GIC8CQA0HRLmjYuUUG27YM18XwmT7KY6C3KCoAphFyLPMsYNn
                    fZYnuFTBY1kRWLRA3+5suf4N2poeAgaKs3vg+KfMLxo=
                    -----END RSA PRIVATE KEY-----
          repos:
            config-repo3:
              uri: git@github.com:istar588/config-repo3.git
              name: config-repo3
              pattern:
              - config-repo3/*
              private-key: |
                    -----BEGIN RSA PRIVATE KEY-----
                    MIICXgIBAAKBgQDKSXIRGz7NwFiXxut3o4DBJbzyMtyWGOD2AtDQyaSNuFuzXi8f
                    U4hTXxIV/lCeuXajaIdz4y10VrmV4LVnLQlo2WCtoihwyAoho3+7RMwjI0+glbfZ
                    uP8mCdm5PDMP14eHtlCPwaMofncLuwtc19cfEvutoCrxlXD39Ullyri1YQIDAQAB
                    AoGBAKv+tMD8xHKXB/zNAqqv16riVnwsaMgqkSQ7kqbjvElPppClFTXyhWg13p/a
                    o1vB37DjEMClOaHAl31rGXKHpYYAZLdTPihJrkSoH4sD05sRkwo5tqjreJGWYhBF
                    WuRRC3NvboQeOHVkuWVcnJvvEnNFmX5nBnv2269J03aO44oRAkEA7iiBnDmsq6Bh
                    pYGTdHCWTyyFJsB+RC/13gH5Q8Zkjmab+HQM7eIRPoHn/Iht4H59p7k2JFTpInqV
                    wRr6y84zHQJBANlw/AvvXY5zgaN1oWRRk6G783J0J443o/xJI8fzaZp0ktc51Yqg
                    YKw5b5f3di7KkYzwwU80Us3KW28uOlLdVBUCQFVbnUCiBzooLHdGXtQv+h98ZGjE
                    Oz0zN1sPuAhLlgTXz/UXmv6ztNyDcOM4/rCkhWLU5gvVhw19hCkHA3aCfB0CQQCk
                    RQY1Yg10+/A5dDmMV1DIA/0kP3pOp9xcUUkV2t+yD1WMAaZAx26hTfbvgMUpDmIt
                    bwkrdCUGUVUIRo1LYugNAkEAziN+MHYv49kA3jEAHe+L0yr5Gv4Oo609UjlFBBHt
                    ZnDecxYYc+cXl6PxwYCXNkH3iFhzyl/fE8cJfZo5KE1NvQ==
                    ----s-END RSA PRIVATE KEY-----